import {test,expect} from '@playwright/test';
import {readdirSync,readFileSync} from 'node:fs';
function files(dir:string):string[]{return readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?files(dir+'/'+e.name):e.name.endsWith('.svg')?[dir+'/'+e.name]:[]);}
const assets=files('backend/assets').map(path=>({key:path.slice('backend/assets'.length),mime:'image/svg+xml',content:readFileSync(path,'utf8')}));
test('register, sign out and sign in; Google remains disabled',async({page})=>{
 let signedIn=false;
 const user={id:'55555555-5555-4555-8555-555555555555',email:'zen@example.com',displayName:'Zen'};
 await page.route('**/api/**',async route=>{const path=new URL(route.request().url()).pathname;if(path==='/api/auth/me')return route.fulfill({status:signedIn?200:401,json:signedIn?{user}:{error:'Sign in required'}});if(path==='/api/assets/catalog')return route.fulfill({json:{assets}});if(path==='/api/auth/register'||path==='/api/auth/login')return route.fulfill({json:{otpRequired:true,expiresIn:300,method:'development-fixed'}});if(path==='/api/auth/verify-otp'){if(route.request().postDataJSON().otp!=='904530')return route.fulfill({status:401,json:{error:'Invalid or expired verification code'}});signedIn=true;return route.fulfill({json:{user}});}if(path==='/api/auth/logout'){signedIn=false;return route.fulfill({json:{ok:true}});}return route.fulfill({status:404,json:{error:'Not found'}});});
 await page.goto('/');await expect(page.getByRole('heading',{name:'Welcome back'})).toBeVisible();await expect(page.getByRole('button',{name:'Continue with Google'})).toBeDisabled();await page.getByRole('button',{name:'Create an account',exact:true}).click();await page.getByLabel('Name',{exact:true}).fill('Zen');await page.getByLabel('Email',{exact:true}).fill(user.email);await page.getByLabel('Password',{exact:true}).fill('a secure password phrase');await page.getByRole('button',{name:'Create account',exact:true}).click();await expect(page.getByRole('heading',{name:'Verify your sign-in'})).toBeVisible();await page.getByLabel('Verification code',{exact:true}).fill('000000');await page.getByRole('button',{name:'Verify and sign in'}).click();await expect(page.getByRole('alert')).toContainText('Invalid');await page.getByLabel('Verification code',{exact:true}).fill('904530');await page.getByRole('button',{name:'Verify and sign in'}).click();await page.getByRole('button',{name:'Simple diagram',exact:true}).click();await page.getByRole('button',{name:'Account and projects'}).click();await page.getByRole('button',{name:'Sign out',exact:true}).click();await expect(page.getByRole('heading',{name:'Welcome back'})).toBeVisible();await page.getByLabel('Email',{exact:true}).fill(user.email);await page.getByLabel('Password',{exact:true}).fill('a secure password phrase');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByLabel('Verification code',{exact:true}).fill('904530');await page.getByRole('button',{name:'Verify and sign in'}).click();await expect(page.getByRole('button',{name:'Account and projects'})).toHaveText('Zen');
});
test('backend failures remain recoverable',async({page})=>{await page.route('**/api/auth/me',route=>route.fulfill({status:503,json:{error:'Service unavailable'}}));await page.goto('/');await expect(page.getByRole('alert')).toContainText('Service unavailable');await expect(page.getByRole('button',{name:'Retry connection'})).toBeVisible();await expect(page.getByRole('button',{name:'Continue with Google'})).toBeDisabled();});
test('account snapshot revisions survive reload and conflicts preserve the local project',async({page})=>{
 let revision=0;
 const user={id:'66666666-6666-4666-8666-666666666666',email:'account@example.com',displayName:'Account'};
 await page.route('**/api/**',async route=>{const request=route.request(),path=new URL(request.url()).pathname;if(path==='/api/auth/me')return route.fulfill({json:{user}});if(path==='/api/assets/catalog')return route.fulfill({json:{assets}});if(path==='/api/projects')return route.fulfill({json:{projects:[]}});if(path.startsWith('/api/projects/')&&request.method()==='PUT'){const input=request.postDataJSON();if(input.revision!==revision)return route.fulfill({status:409,json:{error:'Project changed in another session. Reload before saving.'}});revision++;return route.fulfill({json:{revision}});}return route.fulfill({status:404,json:{error:'Not found'}});});
 await page.goto('/');await page.getByRole('button',{name:'Plan with costs',exact:true}).click();await page.getByRole('button',{name:'Account and projects'}).click();await page.getByRole('button',{name:'Save to account',exact:true}).click();await expect(page.getByText('Saved to your account.',{exact:true})).toBeVisible();expect(revision).toBe(1);
 await page.reload();await page.getByRole('button',{name:'Account and projects'}).click();await page.getByRole('button',{name:'Save to account',exact:true}).click();await expect(page.getByText('Saved to your account.',{exact:true})).toBeVisible();expect(revision).toBe(2);
 revision++;await page.getByRole('button',{name:'Save to account',exact:true}).click();await expect(page.getByRole('alert')).toContainText('changed in another session');await expect(page.locator('.react-flow__node-service')).toHaveCount(4);
});
test('throttled logins show cooldown and expired OTP steps can be restarted',async({page})=>{
 let attempts=0,verifications=0;
 await page.route('**/api/**',route=>{const path=new URL(route.request().url()).pathname;if(path==='/api/auth/me')return route.fulfill({status:401,json:{error:'Sign in required'}});if(path==='/api/auth/login'){attempts++;return attempts===1?route.fulfill({status:429,headers:{'Retry-After':'2'},json:{error:'Too many attempts'}}):route.fulfill({json:{otpRequired:true,expiresIn:1,method:'development-fixed'}});}if(path==='/api/auth/verify-otp'){verifications++;return route.fulfill({status:401,json:{error:'Expired'}});}if(path==='/api/auth/logout')return route.fulfill({json:{ok:true}});return route.fulfill({status:404});});
 await page.goto('/');await page.getByLabel('Email',{exact:true}).fill('otp@example.com');await page.getByLabel('Password',{exact:true}).fill('a long password phrase');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Too many');await expect(page.getByRole('button',{name:'Sign in',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Sign in',exact:true})).toBeEnabled({timeout:5000});await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('heading',{name:'Verify your sign-in'})).toBeVisible();await expect(page.getByText('Verification expired. Start again.',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Verify and sign in'})).toBeDisabled();await page.getByRole('button',{name:'Start again'}).click();await expect(page.getByRole('heading',{name:'Welcome back'})).toBeVisible();expect(verifications).toBe(0);
});
