import { describe,it,expect } from 'vitest';
import JSZip from 'jszip';
import {sampleProject} from '@planner/domain/examples';
import {layoutProject} from '@planner/domain/diagram/layout';
import {drawioXml,graphSvg,reportMarkdown,exportArtifact,blobBytes} from './artifacts';
describe('editable exports',()=>{
 it('escapes labels, preserves nested groups and editable connectors',async()=>{const p=sampleProject();p.variants[0].resources[0].name='API <unsafe> & "quoted"';p.variants[0].connections[0].label='A & B';const graph=await layoutProject(p);const xml=new DOMParser().parseFromString(drawioXml(graph),'application/xml');expect(xml.querySelector('parsererror')).toBeNull();expect(xml.querySelectorAll('mxCell[vertex="1"]')).toHaveLength(5);expect(xml.querySelectorAll('mxCell[edge="1"]')).toHaveLength(3);const resource=xml.getElementById(p.variants[0].resources[0].id)??Array.from(xml.querySelectorAll('mxCell')).find(n=>n.getAttribute('id')===p.variants[0].resources[0].id);expect(resource?.getAttribute('value')).toBe('API <unsafe> & "quoted"');expect(resource?.getAttribute('parent')).toBe(p.variants[0].boundaries[0].id);expect(xml.querySelector('image')).toBeNull();expect(resource?.getAttribute('style')).toContain('image=data:image/svg+xml,');const svg=new DOMParser().parseFromString(graphSvg(graph),'image/svg+xml');expect(svg.querySelector('parsererror')).toBeNull();expect(svg.querySelectorAll('text')).toHaveLength(8);expect(svg.querySelector('unsafe')).toBeNull();expect(svg.querySelectorAll('image')).toHaveLength(4);expect(svg.querySelector('image')?.getAttribute('href')).toMatch(/^data:image\/svg\+xml,/);});
 it('includes assumptions, all variants, cost completeness and source information',()=>{const p=sampleProject();const text=reportMarkdown(p);expect(text).toContain('## Assumptions');expect(text).toContain('## Manual');expect(text).toContain('Known monthly subtotal');expect(text).toContain('Pricing sources');expect(text).toContain('730 hours');expect(text).toContain('Estimate date');});
 it('generates portable canonical JSON and actual binary documents in a bundle',async()=>{const p=sampleProject();const json=await exportArtifact(p,'json');expect(JSON.parse(new TextDecoder().decode(await blobBytes(json)))).toEqual(p);const bundle=await exportArtifact(p,'zip');const zip=await JSZip.loadAsync(await blobBytes(bundle));expect(await zip.file('README.txt')!.async('string')).toContain('PNG unavailable');expect(Object.keys(zip.files)).toEqual(expect.arrayContaining(['architecture.json','architecture.drawio','architecture.svg','architecture.md','architecture.pdf','architecture.docx']));expect((await zip.file('architecture.pdf')!.async('string')).slice(0,4)).toBe('%PDF');const docx=await JSZip.loadAsync(await zip.file('architecture.docx')!.async('uint8array'));expect(await docx.file('word/document.xml')!.async('string')).toContain('Assumptions');});
 it('uses parent-relative geometry for nested boundary children',()=>{const graph={width:400,height:300,nodes:[{id:'outer',label:'Cloud',kind:'boundary' as const,x:20,y:30,width:300,height:200},{id:'inner',label:'Network',kind:'boundary' as const,parentId:'outer',x:50,y:80,width:200,height:100}],edges:[]};const xml=new DOMParser().parseFromString(drawioXml(graph),'application/xml');const cell=xml.querySelector('mxCell[id="inner"]');expect(cell?.getAttribute('parent')).toBe('outer');expect(cell?.querySelector('mxGeometry')?.getAttribute('x')).toBe('30');expect(cell?.querySelector('mxGeometry')?.getAttribute('y')).toBe('50');});
 it('rejects invalid project before export',async()=>{const p=sampleProject();p.activeVariantId=crypto.randomUUID();await expect(exportArtifact(p,'svg')).rejects.toThrow();});
});
