import { useState } from 'react';
import { excelExport, excelImport, imageImport, mermaidExport, rasterExport, textImport, xmlExport, type DocumentData } from '@planner/adapters/exports/interchange';
import { downloadArtifact } from '@planner/adapters/platform/download';
export function FileTransfers({data,projectId,architecture,onImport,onImage,onError}:{data?:DocumentData;projectId:string;architecture:boolean;onImport:(data:DocumentData)=>Promise<void>;onImage:(image:Awaited<ReturnType<typeof imageImport>>)=>Promise<void>;onError:(message:string)=>void}){
 const [busy,setBusy]=useState(false);
 const run=async(task:()=>Promise<void>)=>{setBusy(true);try{await task();}catch(error){onError(error instanceof Error?error.message:'File transfer failed');}finally{setBusy(false);}};
 const save=(format:'mmd'|'xml'|'xlsx'|'png'|'jpeg')=>run(async()=>{if(!data)return;const blob=format==='mmd'?new Blob([mermaidExport(data)],{type:'text/plain'}):format==='xml'?new Blob([await xmlExport(data)],{type:'application/xml'}):format==='xlsx'?await excelExport(data):await rasterExport(data,format);await downloadArtifact(blob,`diagram.${format}`);});
 return <><div className="export-grid">{(['mmd','xml','xlsx',...(architecture?[]:['png'] as const),'jpeg'] as const).map(format=><button key={format} disabled={busy||!data} onClick={()=>void save(format)}>Export {format==='mmd'?'Mermaid':format.toUpperCase()}</button>)}</div><label className="interchange-import">Import Mermaid, XML, Excel or image<input aria-label="Import Mermaid, XML, Excel or image" disabled={busy} type="file" accept=".mmd,.mermaid,.xml,.drawio,.xlsx,.png,.jpg,.jpeg" onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;void run(async()=>{if(file.size>10_000_000)throw new Error('Import file exceeds 10 MB');const extension=file.name.split('.').at(-1)?.toLowerCase();if(['png','jpg','jpeg'].includes(extension??'')){await onImage(await imageImport(file));return;}const data=extension==='xlsx'?await excelImport(await file.arrayBuffer()):textImport(await file.text(),extension==='mmd'||extension==='mermaid'?'mmd':'xml',projectId);await onImport(data);});}}/></label><p className="hint">Excel: XLSX files exported here; edit the Diagram table. XML: uncompressed Draw.io. Plain Mermaid: flowcharts, sequences and ER diagrams (supported syntax). PNG/JPEG imports are movable reference images in a simple diagram. Images do not become cloud resources.</p>{busy&&<p role="status">Processing file…</p>}</>;
}
