import { assetUrl } from '@planner/adapters/backend/assets';
import { useEffect, useRef, useState } from 'react';
import { ReactFlow, Background, Controls, Handle, Position, MarkerType, applyNodeChanges, type Node, type NodeProps, type Edge, type ReactFlowInstance } from '@xyflow/react';
import { drawingLayout, editDrawing, removeDrawingNode, type Drawing, type DrawingNode } from '@planner/domain/drawings/model';
import { assetLibraries, drawingAsset, drawingAssets, libraryNames, type AssetLibrary } from '@planner/domain/drawings/assets';
import { drawingSvg } from '@planner/adapters/exports/drawings';
type ShapeData = { node: DrawingNode };
function ShapeNode({ data }: NodeProps<Node<ShapeData>>) {
    const n = data.node, asset = n.assetId ? drawingAsset(n.assetId) : undefined;
    if(n.shape === 'image') return <div style={{width:'100%',height:'100%'}}><Handle type="target" position={Position.Left}/><img className="reference-image" draggable={false} src={n.imageData} alt={n.label} style={{width:'100%',height:'100%',objectFit:'contain'}}/><Handle type="source" position={Position.Right}/></div>;
    return <div className={`drawing-node shape-${n.shape}`}><Handle type="target" position={Position.Left}/>{asset && <img src={assetUrl(asset.icon)} alt=""/>}<strong>{n.label}</strong>{n.shape === 'entity' && <div className="entity-fields">{n.fields.map((field, index) => <div key={index}>{field}</div>)}</div>}<Handle type="source" position={Position.Right}/></div>;
}
const nodeTypes = { shape: ShapeNode };
export function DrawingEditor({ drawing, onChange, shapesOpen, onCloseShapes, onError, initialLibrary }: { initialLibrary: AssetLibrary; drawing: Drawing; onChange: (d: Drawing) => void; shapesOpen: boolean; onCloseShapes: () => void; onError: (message: string) => void }) {
    const flow = useRef<ReactFlowInstance<Node<ShapeData>, Edge> | null>(null);
    const [selected, setSelected] = useState<string>();
    const [library, setLibrary] = useState<AssetLibrary>(initialLibrary);
    const [search, setSearch] = useState('');
    const [nodes, setNodes] = useState<Node<ShapeData>[]>([]);
    const [pan, setPan] = useState(false);
    const [past, setPast] = useState<Drawing[]>([]), [future, setFuture] = useState<Drawing[]>([]);
    const [from, setFrom] = useState(''), [to, setTo] = useState(''), [label, setLabel] = useState('');
    const graph = drawingLayout(drawing);
    useEffect(() => { setNodes(drawingLayout(drawing).nodes.map(n => ({ id: n.id, type: 'shape', position: { x: n.x, y: n.y }, data: { node: n }, style: { width: n.width, height: n.height } }))); }, [drawing]);
    const update = (edit: (d: Drawing) => void) => { try { const next = editDrawing(drawing, edit); setPast(p => [...p.slice(-49), drawing]); setFuture([]); onChange(next); } catch (error) { onError(error instanceof Error ? error.message : 'Invalid drawing edit'); } };
    const node = drawing.nodes.find(n => n.id === selected), edge = drawing.edges.find(e => e.id === selected);
    const add = (shape: DrawingNode['shape'], assetId?: string, position?: { x: number; y: number }) => {
        const id = crypto.randomUUID(); update(d => { d.nodes.push({ id, label: assetId ? drawingAsset(assetId)!.label : shape === 'entity' ? 'Entity' : shape === 'participant' ? 'Participant' : shape === 'decision' ? 'Decision?' : shape === 'terminal' ? 'Start / End' : shape === 'data' ? 'Input / Output' : 'Process', shape, assetId, fields: shape === 'entity' ? ['id: UUID PK', 'name: text'] : [], x: position?.x ?? 80 + (d.nodes.length % 3) * 300, y: position?.y ?? 100 + Math.floor(d.nodes.length / 3) * 180 }); }); setSelected(id);
    };
    const connect = (source: string, target: string, text = '') => update(d => { d.edges.push({ id: crypto.randomUUID(), source, target, label: text || (d.kind === 'sequence' ? 'Message' : 'Connection'), ...(d.kind === 'er' ? { relation: '1:N' as const } : {}) }); });
    const edges: Edge[] = drawing.edges.map(e => ({ ...e, label: `${e.label}${e.relation ? ` (${e.relation})` : ''}`, selected: e.id === selected }));
    const undo = () => { const previous = past.at(-1); if (previous) { setPast(past.slice(0, -1)); setFuture([drawing, ...future]); onChange(previous); setSelected(undefined); } };
    const redo = () => { const next = future[0]; if (next) { setFuture(future.slice(1)); setPast([...past, drawing]); onChange(next); setSelected(undefined); } };
    useEffect(() => {
        const key = (event: KeyboardEvent) => {
            if (event.key === 'Escape') setSelected(undefined);
            const target = event.target as HTMLElement;
            if (['INPUT', 'TEXTAREA', 'SELECT'].includes(target.tagName) || target.isContentEditable) return;
            if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'z') { event.preventDefault(); if (event.shiftKey) redo(); else undo(); }
            if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'y') { event.preventDefault(); redo(); }
        };
        window.addEventListener('keydown', key);
        return () => window.removeEventListener('keydown', key);
    });
    return <section className="contextual-editor drawing-editor" aria-label={`${drawing.kind} editor`}>
        <div className="editor-body"><div className="editor-canvas" onDragOver={e => { if (drawing.kind !== 'sequence' && e.dataTransfer.types.includes('application/x-planner-shape')) { e.preventDefault(); e.dataTransfer.dropEffect = 'copy'; } }} onDrop={e => {
            if (!flow.current || drawing.kind === 'sequence') return;
            try { const data: unknown = JSON.parse(e.dataTransfer.getData('application/x-planner-shape')); if (typeof data !== 'object' || data === null || !('shape' in data) || typeof data.shape !== 'string') return;
                const allowed = drawing.kind === 'infrastructure' ? ['asset'] : drawing.kind === 'er' ? ['entity'] : ['process', 'decision', 'terminal', 'data']; if (!allowed.includes(data.shape)) return;
                const assetId = 'assetId' in data && typeof data.assetId === 'string' ? data.assetId : undefined; if (data.shape === 'asset' && (!assetId || !drawingAsset(assetId))) return;
                e.preventDefault(); const position = flow.current.screenToFlowPosition({ x: e.clientX, y: e.clientY }); add(data.shape as DrawingNode['shape'], assetId, { x: Math.round(position.x / 20) * 20, y: Math.round(position.y / 20) * 20 });
            } catch { /* Ignore unrelated drag payloads. */ }
        }}>{drawing.kind === 'sequence' ? <div className="sequence-canvas" aria-label="Sequence diagram"><div className="sequence-svg" onClick={e => { const target = e.target as Element; const item = target.closest('[data-node-id], [data-edge-id]'); if (item) setSelected(item.getAttribute('data-node-id') ?? item.getAttribute('data-edge-id') ?? undefined); else setSelected(undefined); }} dangerouslySetInnerHTML={{ __html: drawingSvg(drawing) }}/></div> : <ReactFlow onInit={instance => { flow.current = instance; }} nodes={nodes} edges={edges} nodeTypes={nodeTypes} onNodesChange={changes => setNodes(previous => applyNodeChanges(changes, previous))} onNodeClick={(_, n) => setSelected(n.id)} onEdgeClick={(_, e) => setSelected(e.id)} onPaneClick={() => setSelected(undefined)} onNodeDragStop={(_, n) => update(d => { const item = d.nodes.find(node => node.id === n.id)!; item.x = n.position.x; item.y = n.position.y; })} onConnect={c => { if (c.source && c.target) connect(c.source, c.target); }} nodesDraggable={!pan} panOnDrag={pan ? true : [1, 2]} snapToGrid snapGrid={[20, 20]} deleteKeyCode={null} defaultEdgeOptions={{ type: 'smoothstep', markerEnd: { type: MarkerType.ArrowClosed } }} fitView fitViewOptions={{ maxZoom: 1 }}><Background/><Controls/></ReactFlow>}{!drawing.nodes.length && <p className="drawing-empty">Open Shapes to start your {drawing.kind === 'er' ? 'ER diagram' : drawing.kind}.</p>}</div>
        <aside className="service-palette" aria-label="Drawing shapes" hidden={!shapesOpen}><button className="drawer-close" aria-label="Close shapes" onClick={onCloseShapes}>×</button><h3>{drawing.kind === 'sequence' ? 'Participants' : 'Add shape'}</h3>
            {drawing.kind === 'infrastructure' ? <><select aria-label="Asset library" value={library} onChange={e => setLibrary(e.target.value as AssetLibrary)}>{assetLibraries.map(id => <option value={id} key={id}>{libraryNames[id]}</option>)}</select><input aria-label="Search assets" placeholder="Search assets…" value={search} onChange={e => setSearch(e.target.value)}/><p className="hint">Visual assets only · no cost estimate</p><div className="palette-grid">{drawingAssets.filter(a => a.library === library && a.label.toLowerCase().includes(search.toLowerCase())).map(asset => <button className="palette-service" aria-label={`Add ${asset.label}`} key={asset.id} draggable onDragStart={e => { e.dataTransfer.setData('application/x-planner-shape', JSON.stringify({ shape: 'asset', assetId: asset.id })); e.dataTransfer.effectAllowed = 'copy'; }} onClick={() => add('asset', asset.id)}><img src={assetUrl(asset.icon)} alt=""/>{asset.label}</button>)}</div></> : <div className="palette-grid">{(drawing.kind === 'sequence' ? ['participant'] : drawing.kind === 'er' ? ['entity'] : ['process', 'decision', 'terminal', 'data']).map(shape => <button key={shape} draggable={drawing.kind !== 'sequence'} onDragStart={e => { e.dataTransfer.setData('application/x-planner-shape', JSON.stringify({ shape })); e.dataTransfer.effectAllowed = 'copy'; }} onClick={() => add(shape as DrawingNode['shape'])}>Add {shape}</button>)}</div>}
        </aside>
        <aside className="properties-panel" aria-label="Drawing properties" hidden={!selected}><button className="drawer-close" aria-label="Close properties" onClick={() => setSelected(undefined)}>×</button><h3>Properties</h3>{node && <><label>Label<input aria-label="Shape label" value={node.label} onChange={e => { if (e.target.value) update(d => { d.nodes.find(n => n.id === node.id)!.label = e.target.value; }); }}/></label>{node.shape === 'image' && <><label>Width<input aria-label="Image width" type="number" min="1" max="6000" value={node.imageWidth} onChange={e=>{const width=Number(e.target.value);if(width>0&&width<=6000)update(d=>{const n=d.nodes.find(n=>n.id===node.id)!;n.imageHeight=width*(n.imageHeight!/n.imageWidth!);n.imageWidth=width;});}}/></label></>}{node.shape === 'entity' && <label>Attributes (one per line)<textarea aria-label="Entity attributes" value={node.fields.join('\n')} onChange={e => update(d => { d.nodes.find(n => n.id === node.id)!.fields = e.target.value.split('\n'); })}/></label>}<button className="danger" onClick={() => { setPast([...past, drawing]); setFuture([]); onChange(removeDrawingNode(drawing, node.id)); setSelected(undefined); }}>Delete shape</button></>}{edge && <><label>Label<input aria-label="Connector label" value={edge.label} onChange={e => update(d => { d.edges.find(item => item.id === edge.id)!.label = e.target.value; })}/></label>{drawing.kind === 'er' && <label>Cardinality<select aria-label="Relationship cardinality" value={edge.relation} onChange={e => update(d => { d.edges.find(item => item.id === edge.id)!.relation = e.target.value as '1:1' | '1:N' | 'N:M'; })}>{['1:1', '1:N', 'N:M'].map(value => <option key={value}>{value}</option>)}</select></label>}{drawing.kind === 'sequence' && <label><input type="checkbox" checked={edge.reply ?? false} onChange={e => update(d => { d.edges.find(item => item.id === edge.id)!.reply = e.target.checked; })}/>Reply (dashed)</label>}<button className="danger" onClick={() => { update(d => { d.edges = d.edges.filter(item => item.id !== edge.id); }); setSelected(undefined); }}>Delete connector</button></>}</aside>
        </div>
        <div className="canvas-toolbar" role="toolbar" aria-label="Drawing tools">{drawing.kind !== 'sequence' && <><button aria-pressed={!pan} onClick={() => setPan(false)}>Select</button><button aria-pressed={pan} onClick={() => setPan(true)}>Pan</button></>}<button disabled={!past.length} onClick={undo}>Undo</button><button disabled={!future.length} onClick={redo}>Redo</button></div>
        <details className="connections"><summary>{drawing.kind === 'sequence' ? 'Participants & messages' : 'Shapes & connections'}</summary><div className="resource-list">{drawing.nodes.map(n => <button key={n.id} onClick={e => { setSelected(n.id); e.currentTarget.closest('details')!.open = false; }}>{n.label}</button>)}</div><div className="connection-builder"><select aria-label="Drawing connection source" value={from} onChange={e => setFrom(e.target.value)}><option value="">From</option>{drawing.nodes.map(n => <option key={n.id} value={n.id}>{n.label}</option>)}</select><select aria-label="Drawing connection target" value={to} onChange={e => setTo(e.target.value)}><option value="">To</option>{drawing.nodes.map(n => <option key={n.id} value={n.id}>{n.label}</option>)}</select><input aria-label="Drawing connection label" value={label} onChange={e => setLabel(e.target.value)}/><button disabled={!from || !to || from === to} onClick={() => connect(from, to, label)}>{drawing.kind === 'sequence' ? 'Add message' : 'Connect shapes'}</button></div>{drawing.edges.map((e, index) => <div className="drawing-connection-row" key={e.id}><button onClick={event => { setSelected(e.id); event.currentTarget.closest('details')!.open = false; }}>{drawing.kind === 'sequence' ? `${index + 1}. ` : ''}{e.label}</button>{drawing.kind === 'sequence' && <><button aria-label={`Move message ${index + 1} up`} disabled={index === 0} onClick={() => update(d => { [d.edges[index - 1], d.edges[index]] = [d.edges[index], d.edges[index - 1]]; })}>↑</button><button aria-label={`Move message ${index + 1} down`} disabled={index === drawing.edges.length - 1} onClick={() => update(d => { [d.edges[index], d.edges[index + 1]] = [d.edges[index + 1], d.edges[index]]; })}>↓</button></>}</div>)}</details>
        <span className="canvas-status">{graph.nodes.length} shapes · {graph.edges.length} connections · No cloud pricing</span>
    </section>;
}
