import { useState } from 'react';
import { api,type Account } from '@planner/adapters/backend/client';
import { parseProject,type Project } from '@planner/domain/model';
import { parseDrawing,type Drawing } from '@planner/domain/drawings/model';
import { ProjectRepository,repository } from '@planner/adapters/storage/repository';
import { DrawingRepository,drawingRepository } from '@planner/adapters/storage/drawings';
interface RemoteProject {id:string;name:string;revision:number}
export function AccountPanel({account,project,flush,onLoad,onLogout,onError}:{account:Account;project:Project;flush:()=>Promise<void>;onLoad:(project:Project)=>Promise<void>;onLogout:()=>Promise<void>;onError:(message:string)=>void}){
 const revisionKey='planner-account-revisions:'+account.id;
 const [projects,setProjects]=useState<RemoteProject[]>([]),[revisions,setRevisions]=useState<Record<string,number>>(()=>{try{const value=JSON.parse(sessionStorage.getItem(revisionKey)??'{}');if(value&&typeof value==='object'&&!Array.isArray(value)&&Object.values(value).every(v=>typeof v==='number'&&Number.isInteger(v)&&v>0))return value;}catch{/* Revision loss fails safely with a server conflict. */}return {};}),[busy,setBusy]=useState(false),[status,setStatus]=useState('');
 function remember(id:string,revision?:number){const next={...revisions};if(revision===undefined)delete next[id];else next[id]=revision;setRevisions(next);try{sessionStorage.setItem(revisionKey,JSON.stringify(next));}catch{/* Server revision checks still prevent overwrites. */}}
 async function run(action:()=>Promise<void>){setBusy(true);setStatus('');try{await action();}catch(error){onError(error instanceof Error?error.message:'Account operation failed');}finally{setBusy(false);}}
 async function list(){const result=await api<{projects:RemoteProject[]}>('/projects');setProjects(result.projects);}
 return <section className="account-panel"><h3>{account.displayName}</h3><p>{account.email}</p><p className="hint">Device saves stay on this device. Save to your account to store this project and its diagrams on the server.</p><div className="toolbar"><button disabled={busy} onClick={()=>void run(async()=>{await flush();const result=await api<{revision:number}>(`/projects/${project.id}`,{method:'PUT',body:JSON.stringify({document:project,drawings:await drawingRepository.list(project.id),revision:revisions[project.id]??0})});remember(project.id,result.revision);await list();setStatus('Saved to your account.');})}>Save to account</button><button disabled={busy} onClick={()=>void run(list)}>List account projects</button><button disabled={busy} onClick={()=>void run(async()=>{const old=new ProjectRepository(),oldDrawings=new DrawingRepository();try{const previous=await old.list();if(!previous.length){setStatus('No previous device projects found.');return;}if(!confirm(`Copy ${previous.length} previous device projects into this account’s local workspace? Existing copies are skipped. Nothing is uploaded.`))return;for(const item of previous){if(await repository.load(item.id))continue;for(const drawing of await oldDrawings.list(item.id))await drawingRepository.save(drawing);await repository.save(item);}location.reload();}finally{old.close();oldDrawings.close();}})}>Import previous device projects</button><button disabled={busy} onClick={()=>void run(async()=>{await flush();await onLogout();})}>Sign out</button></div>{status&&<p role="status">{status}</p>}{projects.map(p=><div className="toolbar" key={p.id}><span>{p.name}</span><button disabled={busy} onClick={()=>void run(async()=>{await flush();const result=await api<{document:unknown;drawings:unknown[];revision:number}>(`/projects/${p.id}`),next=parseProject(result.document),drawings=result.drawings.map(parseDrawing);if(drawings.some(d=>d.projectId!==next.id))throw new Error('Invalid account drawing ownership');if(!confirm('Open the account snapshot? This replaces the device copy of this project.'))return;await drawingRepository.transaction('rw',drawingRepository.drawings,async()=>{await drawingRepository.removeProject(next.id);for(const drawing of drawings)await drawingRepository.save(drawing as Drawing);});remember(p.id,result.revision);await onLoad(next);setStatus('Account snapshot opened.');})}>Open account project</button><button disabled={busy} onClick={()=>void run(async()=>{if(!confirm(`Delete ${p.name} from your account? The device copy remains.`))return;await api(`/projects/${p.id}`,{method:'DELETE'});await list();remember(p.id);})}>Delete account project</button></div>)}</section>;
}
