import type { LoadedWorkspace } from '../../app/useWorkspace';
import { activeVariant, commit, newId } from '@planner/domain/model';
import { makeResource } from '@planner/domain/examples';
import { services } from '@planner/domain/providers';
import { Diagram } from '../diagram/Diagram';
import { Inspector } from './Inspector';
export function ArchitecturePanel({ workspace }: {
    workspace: Pick<LoadedWorkspace, 'project' | 'selected' | 'setSelected' | 'change' | 'past' | 'future' | 'undo' | 'redo' | 'service' | 'setService' | 'run' | 'reportError' | 'from' | 'setFrom' | 'to' | 'setTo' | 'connectionLabel' | 'setConnectionLabel'>;
}) {
    const { project, selected, setSelected, change, past, future, undo, redo, service, setService, run, reportError, from, setFrom, to, setTo, connectionLabel, setConnectionLabel } = workspace;
    const v = activeVariant(project);
    return <section className="canvas-panel"><div className="panel-title"><span className="step">02</span><h2>Architecture</h2><select aria-label="Architecture variant" value={project.activeVariantId} onChange={e => { change(commit(project, d => { d.activeVariantId = e.target.value; })); setSelected(undefined); }}>{project.variants.map(v => <option key={v.id} value={v.id}>{v.name}</option>)}</select></div><div className="canvas-toolbar"><button disabled={!past.length} onClick={undo}>Undo</button><button disabled={!future.length} onClick={redo}>Redo</button><button onClick={() => change(commit(project, d => { d.presentation.positions = {}; }))}>Auto layout</button><select aria-label="Service to add" value={service} onChange={e => setService(e.target.value)}><option value="">Choose service</option>{services.filter(s => s.provider === project.provider).map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select><button disabled={!service} onClick={() => run(() => { const r = makeResource(project, service); change(commit(project, d => { activeVariant(d).resources.push(r); })); setSelected(r.id); })}>Add service</button><button onClick={() => run(() => change(commit(project, d => { activeVariant(d).boundaries.push({ id: newId(), name: 'Network boundary', kind: 'network' }); })))}>Add boundary</button></div><Diagram project={project} onChange={change} onSelect={setSelected} selectedId={selected} onError={reportError}/><details className="connections"><summary>Resources & connections · {v.resources.length} services</summary><div className="resource-list">{v.resources.map(r => <button key={r.id} className={selected === r.id ? 'selected' : ''} onClick={() => setSelected(r.id)}>{r.name}</button>)}{v.boundaries.map(b => <button key={b.id} onClick={() => setSelected(b.id)}>{b.name}</button>)}</div><div className="connection-builder"><select aria-label="Connection source" value={from} onChange={e => setFrom(e.target.value)}><option value="">From</option>{v.resources.map(r => <option key={r.id} value={r.id}>{r.name}</option>)}</select><select aria-label="Connection target" value={to} onChange={e => setTo(e.target.value)}><option value="">To</option>{v.resources.map(r => <option key={r.id} value={r.id}>{r.name}</option>)}</select><input aria-label="Connection label" value={connectionLabel} onChange={e => setConnectionLabel(e.target.value)}/><button disabled={!from || !to} onClick={() => run(() => change(commit(project, d => { activeVariant(d).connections.push({ id: newId(), source: from, target: to, label: connectionLabel }); })))}>Connect</button></div>{v.connections.map(c => <button key={c.id} onClick={() => setSelected(c.id)}>{v.resources.find(r => r.id === c.source)?.name} → {v.resources.find(r => r.id === c.target)?.name}: {c.label}</button>)}</details><Inspector project={project} selectedId={selected} onChange={p => run(() => change(p))} onSelect={setSelected}/></section>;
}
