import { describe,it,expect,vi } from 'vitest';
import { sampleProject } from '@planner/domain/examples';
import { newId } from '@planner/domain/model';
import { applyExtraction,answerQuestion,unresolvedCritical,rankedQuestions,generateArchitectures,generationSchema } from './requirements';
const extraction={facts:[{text:'Needs database',critical:true,source:'prd' as const}],unknowns:[{question:'Traffic?',critical:true,impact:'cost' as const}],assumptions:[]};
describe('requirements and canonical generation',()=>{
 it('ranks eight highest-impact questions',()=>{expect(rankedQuestions({...extraction,unknowns:Array.from({length:12},(_,i)=>({question:String(i),critical:i===11,impact:'cost' as const}))})).toHaveLength(8);expect(rankedQuestions({...extraction,unknowns:[...extraction.unknowns,{question:'Availability?',critical:true,impact:'architecture'}]})[0].question).toBe('Availability?');});
 it('labels sources and gates critical unknowns until explicitly resolved',()=>{const p=applyExtraction(sampleProject(),'PRD',extraction);const question=unresolvedCritical(p)[0];expect(p.sources.find(s=>s.id===p.requirements.at(-2)?.sourceId)?.kind).toBe('prd');expect(unresolvedCritical(answerQuestion(p,question.id,'100 users',true))).toEqual([]);});
 it('blocks generation without making an AI request',async()=>{const p=applyExtraction(sampleProject(),'PRD',extraction);const adapter={request:vi.fn()};await expect(generateArchitectures(adapter,p)).rejects.toThrow('critical');expect(adapter.request).not.toHaveBeenCalled();});
 it.each(['aws','azure','gcp'] as const)('atomically validates two %s variants',async provider=>{const p=sampleProject(provider);const variants=p.variants.map(v=>({...v,name:'Lean' as const}));const second=sampleProject(provider).variants[0];variants.push({...second,name:'Recommended' as 'Lean'});variants.forEach(v=>{v.id=newId();v.resources.forEach(r=>{Object.values(r.configuration.inputs).forEach(input=>{if(input.source.kind==='assumption')input.source.id=p.assumptions[0].id;});});});const adapter={request:vi.fn().mockResolvedValue(JSON.stringify({variants}))};const result=await generateArchitectures(adapter,p);expect(result.variants.map(v=>v.name)).toEqual(['Lean','Recommended']);expect(p.variants[0].name).toBe('Manual');});
 it('rejects coordinates and retains original project on failure',async()=>{const p=sampleProject();const snapshot=JSON.stringify(p);const adapter={request:vi.fn().mockResolvedValue('{"variants":[]}')};await expect(generateArchitectures(adapter,p)).rejects.toThrow('one repair');expect(JSON.stringify(p)).toBe(snapshot);expect(generationSchema.safeParse({variants:[],positions:{}}).success).toBe(false);});
});
