import type { LoadedWorkspace } from '../../app/useWorkspace';
import { activeVariant } from '@planner/domain/model';
import { providerName } from '@planner/domain/providers';
import { estimate } from '@planner/domain/pricing';
import { CollapsiblePanel } from '../../shared/components/CollapsiblePanel';
export function CostPanel({ workspace }: {
    workspace: Pick<LoadedWorkspace, 'project' | 'costCollapsed' | 'setCostCollapsed'>;
}) {
    const { project, costCollapsed, setCostCollapsed } = workspace;
    const v = activeVariant(project), cost = estimate(project);
    return <CollapsiblePanel className="cost-panel" step="03" title="Monthly estimate" collapsed={costCollapsed} onToggle={() => setCostCollapsed(value => !value)}><div className="cost-total"><small>Known base subtotal · USD</small><strong data-testid="cost-total">${cost.base.toFixed(2)}</strong><span>per month</span></div><p className={cost.complete ? 'complete' : 'incomplete'}>{!v.resources.length ? 'Add a service to begin estimating' : cost.complete ? 'All resource rates priced' : 'Incomplete estimate — unpriced costs remain'}</p><div className="cost-range"><span>Low<strong>${cost.low.toFixed(2)}</strong></span><span>High<strong>${cost.high.toFixed(2)}</strong></span></div><h3>Resource breakdown</h3>{cost.resources.map(r => <details key={r.resourceId}><summary>{r.name}<strong>{!r.complete && !r.lineItems.length ? 'Unpriced' : `$${r.base.toFixed(2)}${r.complete ? '' : ' + ?'}`}</strong></summary>{r.lineItems.map((line, index) => <div className="price-detail" key={index}><p>{line.formula}</p><p>SKU: {line.rate.sku} · {line.rate.units}</p>{Object.entries(line.inputs).map(([name, input]) => <p key={name}>{name}: {input.value} {input.unit} · {input.source.kind === 'catalog' ? 'documented default' : project.assumptions.find(a => a.id === input.source.id)?.label ?? project.requirements.find(r => r.id === input.source.id)?.text ?? 'input source'}</p>)}<a href={line.rate.source} target="_blank" rel="noreferrer">Rate source · retrieved {line.rate.retrieved}</a></div>)}{r.warnings.map((w, i) => <p className="hint" key={i}>{w}</p>)}</details>)}<h3>Provider subtotals</h3>{[...new Set(v.resources.map(r => r.provider))].map(provider => { const items = cost.resources.filter(item => v.resources.find(r => r.id === item.resourceId)?.provider === provider); return <p className="total-row" key={provider}><span>{providerName[provider]}</span><strong>${items.reduce((sum, item) => sum + item.base, 0).toFixed(2)}{items.every(item => item.complete) ? '' : ' + ?'}</strong></p>; })}<h3>Category totals</h3>{Object.entries(cost.categories).map(([name, total]) => <p className="total-row" key={name}><span>{name}</span><strong>${total.base.toFixed(2)}{total.complete ? '' : ' + ?'}</strong></p>)}<h3>Environment totals</h3>{Object.entries(cost.environments).map(([name, total]) => <p className="total-row" key={name}><span>{name}</span><strong>${total.base.toFixed(2)}{total.complete ? '' : ' + ?'}</strong></p>)}<details><summary>Assumptions & completeness warnings</summary>{cost.warnings.map((w, i) => <p className="hint" key={i}>{w}</p>)}</details><details><summary>Pricing sources</summary>{cost.sources.map(source => <p className="hint" key={source}><a href={source} target="_blank" rel="noreferrer">{new URL(source).hostname}</a></p>)}</details><p className="hint">730-hour month. Taxes, discounts, credits and free tiers excluded. Equal range bounds mean no variability was supplied.</p></CollapsiblePanel>;
}
