import { describe,it,expect } from 'vitest';
import { sampleProject } from '../../core/sample';
import { estimate,instanceHours,containerHours,serverless,database,objectStorage,egress,loadBalancer,costEstimateSchema } from './index';
import {rateCatalogSchema,pricingCatalog} from '../../data/pricing';
describe('deterministic pricing',()=>{
 it('validates strict pricing contracts and required rate dimensions',()=>{expect(costEstimateSchema.safeParse(estimate(sampleProject())).success).toBe(true);const rate=structuredClone(pricingCatalog.find(r=>r.formula==='container')!);rate.rates.cpu=-1;expect(rateCatalogSchema.safeParse(rate).success).toBe(false);delete rate.rates.cpu;expect(rateCatalogSchema.safeParse(rate).success).toBe(false);expect(costEstimateSchema.safeParse({...estimate(sampleProject()),base:-1}).success).toBe(false);});
 it('calculates every formula with explicit units',()=>{expect(instanceHours(730,2,0.1)).toBe(146);expect(containerHours(10,2,1,2,0.04,0.005)).toBe(1);expect(serverless(1e6,1,1,0.2/1e6,0.000016)).toBeCloseTo(16.2);expect(database(10,2,100,0.1,0.02)).toBe(4);expect(objectStorage(100,0.023)).toBe(2.3);expect(egress(100,0.09)).toBe(9);expect(loadBalancer(10,1,20,0.02,0.008)).toBe(0.36);});
 it('reports missing rates as unpriced, preserves known subtotal and provenance',()=>{const p=sampleProject();p.variants[0].resources[0].configuration.sku='unknown';const e=estimate(p);expect(e.complete).toBe(false);const f=e.resources.find(r=>r.name.includes('Fargate'))!;expect(f.base).toBeCloseTo(45.040032);expect(f.lineItems[0].inputs.cpu.source.kind).toBe('assumption');expect(f.lineItems[0].rate.retrieved).toBe('2026-10-06');expect(e.sources[0]).toContain('aws.amazon.com');expect(e.resources.filter(r=>!r.complete).every(r=>r.lineItems.length===0)).toBe(true);expect(e.low).toBe(e.high);});
 it('recalculates ranges and rejects wrong units or unknown SKU',()=>{const p=sampleProject();const r=p.variants[0].resources.find(r=>r.service==='fargate')!;r.configuration.scenarios={low:0.5,high:2};const e=estimate(p).resources.find(x=>x.resourceId===r.id)!;expect(e.high).toBeCloseTo(e.base*2);r.configuration.inputs.cpu.unit='bananas';expect(estimate(p).resources.find(x=>x.resourceId===r.id)?.complete).toBe(false);r.configuration.sku='invented';expect(estimate(p).resources.find(x=>x.resourceId===r.id)?.warnings.join()).toContain('unpriced');});
 it('prices example AWS primary components and verifies per-second conversion',()=>{const p=sampleProject();const e=estimate(p);expect(e.complete).toBe(true);expect(e.resources.find(r=>r.name==='S3')?.base).toBeCloseTo(11.3);expect(e.resources.find(r=>r.name==='RDS PostgreSQL')?.base).toBeCloseTo(32.18);expect(e.resources.find(r=>r.name==='CloudFront')?.base).toBeCloseTo(8.5);expect(e.base).toBeCloseTo(97.020032);});
 it('keeps explicit unpriced transfer incomplete and tier overages unpriced',()=>{const p=sampleProject('azure');const e=estimate(p);expect(e.resources.find(r=>r.category==='container')?.lineItems.length).toBe(1);expect(e.resources.find(r=>r.category==='container')?.complete).toBe(false);const aws=sampleProject();aws.variants[0].resources.find(r=>r.service==='cloudfront')!.configuration.inputs.egress.value=20000;expect(estimate(aws).complete).toBe(false);});
 it('rejects malformed canonical projects before calculating',()=>{const p=sampleProject();p.variants[0].resources[0].configuration.inputs.egress.value=-1;expect(()=>estimate(p)).toThrow();});
 it('does not price impossible provider configurations',()=>{const p=sampleProject();p.variants[0].resources.find(r=>r.service==='fargate')!.configuration.inputs.memory.value=1;expect(estimate(p).resources.find(r=>r.category==='container')?.warnings.join()).toContain('unsupported Fargate');});
});
